#!/usr/bin/env python3
"""
render_system_pages.py — generate the wiki's system pages from the repository.

Creates (as wikitext files plus an index ``pages.tsv``):

  * Category pages for the 26 specialties, article types and status categories
  * MediaWiki:Common.css  (styling of notice boxes, info box, version box)
  * Footer messages  (MediaWiki:Privacy/Aboutsite/Disclaimers + target pages)
  * Wikimedica:Impressum / Datenschutz  (from docs/legal/page-drafts)
  * Wikimedica:Haftungsausschluss  (generated from data/legal/disclaimers.yaml, never typed by hand)
  * the main page (Hauptseite)

The pages are applied with ``infra/deploy/bootstrap-wiki.sh`` through MediaWiki's
maintenance script ``edit.php`` (no API credentials needed, runs on the server).

Production guard: the legal drafts contain placeholders such as [[ANSCHRIFT]] or
[PRÜFEN] for real company data. With --env production the script REFUSES to render
while any placeholder is left, and also while the disclaimers are not approved by Legal.

Usage:
    python scripts/publishing/render_system_pages.py --env staging --out build/system-pages
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(HERE))

import md2wiki as m2w  # noqa: E402
import wikipage  # noqa: E402

PLACEHOLDER_RE = re.compile(r"\[\[[^\]]*[A-ZÄÖÜ]{3,}[^\]]*\]\]|\[PRÜFEN[^\]]*\]|\[Entscheidung [^\]]*\]|\[Dienstleister[^\]]*\]|\[Je nach[^\]]*\]|\[Versanddienstleister[^\]]*\]")

CSS = """\
/* Wikimedica — generated by scripts/publishing/render_system_pages.py. Do not edit by hand. */
.wm-notices { margin: 0 0 1em 0; }
.wm-notice { border-left: 4px solid #757575; background: rgba(117, 117, 117, .10);
             padding: .6em .9em; margin: 0 0 .5em 0; border-radius: 0 3px 3px 0; }
.wm-notice.wm-emergency { border-left-color: #c62828; background: rgba(198, 40, 40, .12); font-size: 1.05em; }
.wm-notice.wm-withdrawn { border-left-color: #ef6c00; background: rgba(239, 108, 0, .12); }
.wm-infobox { float: right; clear: right; margin: 0 0 1em 1em; max-width: 24em; }
.wm-infobox th { text-align: left; white-space: nowrap; vertical-align: top; }
.wm-versionbox { margin-top: 1.5em; font-size: .9em; }
@media print { .wm-infobox { float: none; max-width: none; } }
"""


def tsv_name(title: str) -> str:
    return re.sub(r"[^A-Za-z0-9ÄÖÜäöüß._-]+", "_", title) + ".wiki"


def category_page(name: str, text: str) -> tuple[str, str]:
    return f"Category:{name}", text + "\n"


def build_pages(env: str, schema: dict, disclaimers: dict) -> dict[str, str]:
    pages: dict[str, str] = {}
    specialties = schema["fields"]["specialty"]["values"]

    for s in specialties:
        if s == "Gender-Medizin":
            text = ("Querschnittsthema und redaktioneller Schwerpunkt von Wikimedica: geschlechtersensible "
                    "Medizin. Diese Kategorie sammelt Artikel des Fachgebiets Gender-Medizin sowie Artikel "
                    "anderer Fachgebiete, in denen geschlechtsspezifische Aspekte relevant sind.")
        else:
            text = f"Artikel des Fachgebiets {s}."
        title, body = category_page(s, text)
        pages[title] = body

    for label, text in {
        "Artikeltyp: Fachartikel": "Fachartikel für medizinisches Fachpersonal.",
        "Artikeltyp: Patienteninformation": "Verständliche Informationen für Patientinnen, Patienten und Angehörige.",
        "Artikeltyp: Aufklärungsmodul": "Modulare Informationsgrundlagen für Aufklärungsgespräche.",
        "Artikeltyp: Entlassinformation": "Informationen zu Entlassung, Nachsorge und Wundversorgung.",
        "Artikeltyp: Arzneimittel (Pharmaka)": "Strukturierte Wirkstoffinformationen für Fachpersonal.",
        "Artikeltyp: Therapieprotokoll": "Evidenzbasierte Therapieprotokolle für Fachpersonal.",
        "Artikeltyp: Leitlinien-Zusammenfassung": "Eigene Zusammenfassungen von Leitlinien; maßgeblich ist stets die Original-Leitlinie.",
        "Artikeltyp: Medienverweis": "Verweise auf Videos, Audio und Animationen zu Patienteninformationen.",
        "Risikoklasse: hoch": "Artikel mit Medical-Advisor-Freigabe (z. B. Arzneimittel, Notfall, Intensivmedizin, Onkologie).",
        "Gesperrt (Sicherheitsprüfung)": "Artikel, die vorübergehend wegen einer Sicherheitsprüfung nicht angezeigt werden.",
        "Zurückgezogen": "Zurückgezogene Artikel.",
        "Archiviert": "Archivierte, nicht mehr aktuelle Artikel.",
    }.items():
        title, body = category_page(label, text)
        pages[title] = body

    title, body = category_page("Rechtliches", "Rechtliche Hinweise, Haftungsausschluss und Datenschutz.")
    pages[title] = body
    pages["MediaWiki:Common.css"] = CSS
    # Footer links: link text and target page of MediaWiki's standard footer messages.
    pages.update({
        "MediaWiki:Aboutsite": "Impressum", "MediaWiki:Aboutpage": "Wikimedica:Impressum",
        "MediaWiki:Privacy": "Datenschutz", "MediaWiki:Privacypage": "Wikimedica:Datenschutz",
        "MediaWiki:Disclaimers": "Haftungsausschluss", "MediaWiki:Disclaimerpage": "Wikimedica:Haftungsausschluss",
    })

    drafts = REPO / "docs" / "legal" / "page-drafts"
    for name, title in [("impressum.md", "Wikimedica:Impressum"), ("datenschutz.md", "Wikimedica:Datenschutz")]:
        pages[title] = _convert_draft((drafts / name).read_text(encoding="utf-8"))

    pages["Wikimedica:Haftungsausschluss"] = _disclaimer_page(disclaimers)
    pages["Hauptseite"] = _main_page(specialties, disclaimers)
    return pages


def _convert_draft(markdown: str) -> str:
    # drop the draft's own banner/meta lines (document version, owner, "do not publish" note)
    body = re.sub(r"^\*\*(Document version|Owner|Last updated):\*\*.*$", "", markdown, flags=re.M)
    body = re.sub(r"^> .*(?:\n> .*)*", "", body, flags=re.M)
    return m2w.convert(body, m2w.ConvertContext(drop_first_h1=True))


def _disclaimer_page(disclaimers: dict) -> str:
    parts = []
    for name in ("emergency", "general", "patient", "professional", "dosing", "consent", "discharge",
                 "guideline_summary", "media", "ai_assisted"):
        block = disclaimers["blocks"][name]
        parts.append(f"== {m2w.esc(block['title'])} ==\n\n{m2w.esc(block['text'])}\n")
    return "\n".join(parts) + "\n[[Category:Rechtliches]]\n"


def _main_page(specialties: list[str], disclaimers: dict) -> str:
    emergency = wikipage.render_notice(disclaimers["blocks"]["emergency"])
    general = wikipage.render_notice(disclaimers["blocks"]["general"])
    links = "\n".join(f"* [[:Category:{s}|{m2w.esc(s)}]]" for s in specialties)
    return f"""<div class="wm-notices">
{emergency}
{general}
</div>

= Wikimedica =

'''Medizinisches Wissen. Strukturiert. Geprüft.''' Wikimedica ist eine modulare, evidenzbewusste
Wissensplattform für medizinisches Fachpersonal und für Patientinnen und Patienten. Alle Artikel
werden vor der Veröffentlichung von qualifizierten Fachpersonen geprüft.

== Fachgebiete ==

{links}

== Nach Zielgruppe ==

* [[:Category:Artikeltyp: Patienteninformation|Informationen für Patientinnen und Patienten]]
* [[:Category:Artikeltyp: Fachartikel|Fachartikel für medizinisches Fachpersonal]]
* [[:Category:Artikeltyp: Arzneimittel (Pharmaka)|Arzneimittel]]
* [[:Category:Artikeltyp: Aufklärungsmodul|Aufklärungsmodule]]
* [[:Category:Artikeltyp: Entlassinformation|Entlassinformationen]]

== Schwerpunkt ==

* [[:Category:Gender-Medizin|Gender-Medizin]] — geschlechtersensible Medizin als Querschnittsthema
"""


def placeholders_left(pages: dict[str, str]) -> list[str]:
    found = []
    for title, text in pages.items():
        # converted text escapes brackets as entities; check the escaped form as well
        plain = text.replace("&#91;", "[").replace("&#93;", "]")
        if PLACEHOLDER_RE.search(plain):
            found.append(title)
    return found


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render the wiki's system pages.")
    p.add_argument("--env", required=True, choices=["staging", "production"])
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--schema", default=str(REPO / "data/metadata/article-schema.yaml"))
    p.add_argument("--disclaimers", default=str(REPO / "data/legal/disclaimers.yaml"))
    args = p.parse_args(argv)

    schema = yaml.safe_load(Path(args.schema).read_text(encoding="utf-8"))
    disclaimers = yaml.safe_load(Path(args.disclaimers).read_text(encoding="utf-8"))
    pages = build_pages(args.env, schema, disclaimers)

    if args.env == "production":
        if disclaimers.get("review_status") != "approved":
            print("GATE: disclaimers are not approved by the Legal Reviewer; refusing to render for production",
                  file=sys.stderr)
            return 2
        left = placeholders_left(pages)
        if left:
            print("GATE: unresolved legal placeholders (real company data) in: " + ", ".join(left)
                  + "\nFill them in docs/legal/page-drafts/ and have Legal review them.", file=sys.stderr)
            return 2

    args.out.mkdir(parents=True, exist_ok=True)
    with (args.out / "pages.tsv").open("w", encoding="utf-8") as index:
        for title in sorted(pages):
            name = tsv_name(title)
            (args.out / name).write_text(pages[title], encoding="utf-8")
            index.write(f"{title}\t{name}\n")
    print(f"rendered {len(pages)} system pages to {args.out} for {args.env}")
    if args.env == "staging" and (left := placeholders_left(pages)):
        print("NOTE: legal pages still contain placeholders (fine for staging): " + ", ".join(left))
    return 0


if __name__ == "__main__":
    sys.exit(main())
